name: Cleanup Stale Temp Uploads

on:
  schedule:
    # Run daily at 03:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run cleanup script (TTL 24h)
        run: pnpm dlx tsx scripts/cleanup-new-uploads.ts --ttl=24 --dry-run=false
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}


